### PR TITLE
Lexer fixes

### PR DESCRIPTION
**Pull request by CyberShadow**
Thank you for this very nice tool!

Here are some lexer improvements that fix some mismatched coverage in my project.

You are right, though, this is pushing the limits of what regular expressions can do. Adding a proper lexer, or reusing one from bash itself or shellcheck should result in more accurate results.

### CODE REVIEW

**Comment by infertux** [comment]
Thank you very much for those (horrible) regexps ;)

Do you need me to push a new release with that fix to rubygems.org?

[References #25]

**Comment by infertux** [comment]
Nevermind, I just pushed release [1.8.1](https://rubygems.org/gems/bashcov/versions/1.8.1) with your fix. Thanks again.

**Comment by CyberShadow** [comment]
Thanks! That bumped my coverage by [an entire 1.4%](https://coveralls.io/jobs/34235512) :)

**Comment by infertux** [comment]
aconfmgr looks pretty cool. I'll give it a try :)

**Pull request merged**
